### ISSUE TITLE
Bring in existing implementationSets when building/updating source

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#10]
# Summary 
tagging @cspayne 

Changes to the RDA Registry/RDA-Vocabularies files, from which we compile map_storage > prop_sets are released fairly regularly. Changes included in these releases need to be integrated with our prop_sets as they are available. 

The best example would be the deprecation of properties in the element sets, as occurred with [the 5.02 release](https://github.com/RDARegistry/RDA-Vocabularies/releases/tag/v5.0.2).

BEFORE
```
<rdf:Description rdf:about="http://rdaregistry.info/Elements/a/P50045">
	<!-- not deprecated... -->
</rdf:Description>
```
AFTER
```
<!-- Property: is collector agent of -->
<rdf:Description rdf:about="http://rdaregistry.info/Elements/a/P50045">
	<!-- deprecated!! -->
	<reg:status rdf:resource="http://metadataregistry.org/uri/RegStatus/1008"/>
</rdf:Description>
```

## Requirements:
- Bring in changes from RDA-Vocabularies releases (new properties, new labels, changes in status such as deprecation) as needed 
- Preserve existing prop_set > implementation_sets, even when a given property has been deprecated\*\*
- ...

\*\* This has not happened yet that I'm aware of but raises the question of how to indicate in our prop_sets that a given property has been deprecated. map_storage prop_sets do not currently provide any such information. Rather, they are simply built *only* from non-deprecated properties! (See [001_02_source_templates.xsl](https://github.com/uwlib-cams/map_storage/blob/71c45f4a88c65e75f6354a229ab86b181ef736cc/xsl/001_02_source_templates.xsl#L15-L18), which is used to build the prop_sets.) So, providing a fix for this problem would most likely affect the current stylesheets used to build prop_sets (001_01_build_update.xsl and 001_02_source_templates.xsl).

## Older notes

- First unsuccessful attempt [here](https://github.com/uwlib-cams/map_storage/blob/ad020a8e42f81207e70ebf4f37e758b2e26aef10/scripts/build_update_storage_namedTemplates.xsl#L43-L46) and [here](https://github.com/uwlib-cams/map_storage/blob/ad020a8e42f81207e70ebf4f37e758b2e26aef10/scripts/build_update_storage_namedTemplates.xsl#L52-L62).
- [?] Build the doc from external sources, then go back and transform it again, with a key to match on values in the previous instance and copy implementations where they exist?

**Comment by briesenberg07** [comment]
Primary use case at this time is new RDA Registry releases like this one:
https://github.com/RDARegistry/RDA-Vocabularies/releases/tag/v5.0.0

**Comment by briesenberg07** [comment]
💡 Use var to store existing implementation sets at start of build-update transform??

**Comment by briesenberg07** [comment]
Discussion with @gerontakos \:

- Perhaps the update strategy needs to be rethought
   - @briesenberg07 was planning to rewrite prop_sets from scratch, and then "plug back in" implementation_sets
   - Perhaps, per TG, better to retain the existing prop_set (and implementation_sets), and instead query the updated external source to see whether anything has changed

**NOTE**
- rewriting the prop_set, and then "plugging back in" implementation sets where they fit runs the risk of orphaning implementation sets when a prop is deprecated and the IRI no longer exists

**Comment by briesenberg07** [comment]
Hello @gerontakos 

@cspayne outlines a workflow which would make use of both Python and XSLT:

> [RDA Registry Updates Solution.pdf](https://uwnetid.sharepoint.com/:b:/s/og_library_cams/EdZcWHcwcS9ItuD7BurMSMcBZ6l5uoIsOjONiMH1daFFig?e=3Lmopj)\*\*
> \*\* UW NetID access

I want to make sure you have the chance to provide feedback on the proposed plan since you've spent some time thinking about this problem! Any chance you could take a look and, if applicable, provide any feedback in the next week (by next Wednesday, 01-25)? Thank you!

**Comment by gerontakos** [comment]
No need to reply to what I write below. My comments are largely unhelpful; if there's anything that helps, that's great; however, whatever the case, no need to take time formulating a response. So:

It's beyond the Libraries' scope to play a part in the life of the XML tool suite. I would like to continue contributing to that international effort, but that's selfish and not good for our organization. Of course XML tools can run this pipeline easily. I think we're just seeing that Python is more widely adopted and I suppose it's time we move on. 

If you look at the first stage, it seems to be about saving the temp file in a preferred format for later processing. I don't see overwriting as a problem with XSLT as it doesn't overwrite anything unless you go-out-of-your way to tell it to do so. 

Next you update the prop_set files, and the main problem seems to be regenerating localids; I'm not sure why any localids need to be generated at all. But it's another case where a Python pipeline is well understood and seems like an easier solution. Then it should be done.

As for there being a source where deprecated properties are listed, no, I don't know of that list. However, there are the soft-deprecated properties -- I suspect the project hasn't accounted for those. There is an alignment of soft-deprecated properties to preferred properties at [https://www.rdaregistry.info/Aligns/alignSoft2Rec.html](https://www.rdaregistry.info/Aligns/alignSoft2Rec.html); that alignment is a csv file.

In the final stages, I don't have any useful responses to the questions, alas.

If this Python solution is not the most efficient, so what! With the small amount of data we work with, efficiency is not top priority. Results are more important.

It may not update automatically -- but can't the it be scheduled as a "job"? I'm assuming it's a continuous process -- a pipeline -- that's run all at once.
