### ISSUE TITLE
pid attibute validation error

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#2]
In the source file, `<prop>` elements will have an `lid` attribute (see [mockup](https://github.com/uwlib-cams/map_storage/blob/28c1daa212cca503e35968ec10f04091293e8063/map_storage_mockup.xml#L17) for details). This needs to be accounted for in the schema; I have been unsuccessful in doing this so far.

My attempt to simply allow a `pid` attribute in the draft source schema is [here](https://github.com/uwlib-cams/map_storage/blob/28c1daa212cca503e35968ec10f04091293e8063/map_storage.xsd#L55-L56).

Validation error is:
```
Attribute 'pid' is not allowed to appear in element 'prop'.
```

![image](https://user-images.githubusercontent.com/27664966/110740874-965cec00-81e8-11eb-8629-f2af1e64a18e.png)

**Comment by gerontakos** [comment]
@pid or, alternatively, @lid, should work as-is. The schema is a little odd the way //element/@name="prop" invokes top-level prop_type, but this should be a completely acceptable way to do it (this XML Schema instrument supports re-use of the //complexType/@name="prop_type" by any element anywhere in the schema). So you shgould validate.
I cloned and ran in oXygen as-is and it validated.
I validated successfully with Saxon-EE 9.9.1.7. I'm not sure what's wrong on your end: what's your processor?
