### ISSUE TITLE
write a very simple tool to retrieve ordered implementation sets for a given RT ID

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#20]
What's the best, easiest way to do this?
I'm thinking of something that is not a stylesheet but can retrieve a set of results in much the same way that the Oxygen XPath Builder does, but I don't think I can include a sort when using XPath Builder.
Is XQuery useful here? I don't know how to XQuery.
Note to self @briesenberg07 ask @gerontakos

**Comment by gerontakos** [comment]
wht not xslt? You want to extract nodes and sort them, no? It seems like XSLT is a good tool.

**Comment by briesenberg07** [comment]
I got it in my head that XQuery might create something like the results you get with the XPath Builder view (or a "Find all" operation). Not a generated document, but a clickable set of results allow you to navigate the instance. 

See screenshots for XPath Builder results--these are great, but I don't think I can add a sort here (maybe I'm wrong about this?).

[1]
Use XPath Builder to match on the properties I'm outputting to my template
![image](https://user-images.githubusercontent.com/27664966/172681032-758a30f6-c0ff-4246-90cf-640b5e8183f8.png)

[2]
Get results
![image](https://user-images.githubusercontent.com/27664966/172681098-14e755eb-aa14-40d4-aad5-b367d815e237.png)

[3]
Click on results to navigate the instance, check my work, and make changes as needed
![image](https://user-images.githubusercontent.com/27664966/172681265-b0bcf743-1fb0-49ec-adc8-a01b12b11197.png)
e

**Comment by gerontakos** [comment]
Unless there's something I don't know, XQuery is similar to XSLT in that you generate output using some input. This location of a node in the input document and the ability to traverse the input document is, I believe, an oXygen service. However, you could simulate this in XSLT output easily enough. Pop it into HTML, provide a link in a strategic place in the extracted node, etc.  

XPath now has fn:sort(). You might want to check it out. (I still haven't used it.)

**Comment by briesenberg07** [comment]
This isn't important right now. Oxygen XQuery Builder is sufficient to move through implementation_sets when designing templates.

![image](https://user-images.githubusercontent.com/27664966/179325498-4b024942-f1ae-4ca3-9ae2-2e9d8cf0607f.png)
