### ISSUE TITLE
Requesting additional prop_set(s)

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#21]
- Add [University of Washington Libraries RDA Application Profile Extension](https://www.lib.washington.edu/static/public/cams/data/localResources/rdaApplicationProfileExtension.html) properties as a `prop_set` instance.
- Dataset IRI = https://doi.org/10.6069/uwlib.55.d.4
- Needed to reproduce UW CAMS RDA/RDF Sinopia resource templates.

**Comment by briesenberg07** [comment]
Tagging @mcm104 because we discussed this issue at our [2022-07-18 meeting](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/[2022_meetings.docx](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/2022_meetings.docx?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=iOoo9i)?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=iOoo9i)

**Comment by mcm104** [comment]
I (hopefully!) changed everything I needed to to generate an RDA Extension prop set! I pushed all my changes and added the prop set I generated [prop_set_rdaExtension.xml](https://github.com/uwlib-cams/map_storage/blob/main/prop_set_rdaExtension.xml) -- it looked right to me but just need confirmation! @briesenberg07

**Comment by briesenberg07** [comment]
Hi @mcm104 - thanks for working on this!

You [ask whether the `xsl:if` elements for domain and range should be in an `xsl:for-each`](https://github.com/uwlib-cams/map_storage/blob/eb9a48ad82c833243c148f5a2f9c84b03cac843e/xsl/001_02_source_templates.xsl#L58). You're already in a [`for-each \@select="rdf:Description"`](https://github.com/uwlib-cams/map_storage/blob/eb9a48ad82c833243c148f5a2f9c84b03cac843e/xsl/001_02_source_templates.xsl#L47-L49), so I don't think so.

Adding a for-each inside the `xsl:if` node test would be a super-safe way to go in the event that any props have multiple domains and/or ranges to catch these (none of them do).

**Comment by mcm104** [comment]
I've been trying to get the labels, domains, and ranges to populate, and I just can't get it to work... I tested the XPaths directly on the RDA extension RDF and it seemed like they were working just fine. I'm not sure what else would be wrong, where the transform could pull all the properties and their IRIs but not the labels, domains, or ranges...

Any ideas @briesenberg07 ?

**Comment by briesenberg07** [comment]
Hello @mcm104 

I just made some changes in the stylesheet that *should have* fixed the problem...

Our RDA Extension is like [the DC Terms RDF/XML](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.rdf) in that `rdf:Description` elements repeat for each statement on a property. Because of this, it is necessary to use `xsl:for-each-group`, `xsl:for-each select="current-group()"`, `xsl:value-of select="current-group()/[...]"`, etc.

This makes the RDA Extension template very similar to the DC Terms template.

But something is still broken, and I don't know what!!! I suspect something small and trifling. I haven't found it yet.

**Comment by mcm104** [comment]
Finally found the problem!

[In 001_01](https://github.com/uwlib-cams/map_storage/blob/4c326e9851d7d0af57e1e856328a4d957bfee0e4/xsl/001_01_build_update.xsl#L30), it's looking for propset names that start with "rda", then "rdaExtension" -- which means it's running the RDA code on the RDA Extension, because it's hitting that first. I updated (hopefully!) all the necessary places to change the set name to "uwRdaExtension", and [it looks like it's working now!](https://github.com/uwlib-cams/map_storage/blob/main/prop_set_uwRdaExtension.xml)

**Comment by briesenberg07** [comment]
Thank you @mcm104
