### ISSUE TITLE
link to visualization of RDA element hierarchies

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#22]
@gerontakos and @mcm104 and I discussed this on [07-18](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/[2022_meetings.docx](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/2022_meetings.docx?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=9t9vFj)?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=9t9vFj).
Maybe such a visualization(s) are already available elsewhere??

**Comment by mcm104** [comment]
I took a first pass at this visualization! <https://github.com/uwlib-cams/map_storage/blob/main/RDA_hierarchy.html> It's really basic and just uses collapsible bullet points to view narrower properties.

Maybe this isn't what others had in mind, but this is useful for me, so I thought I would share it!

**Comment by briesenberg07** [comment]
This is really cool @mcm104 . Thank you!
I created an html directory to for publishing this and any other HTML in future... it [looks like](https://uwlib-cams.github.io/map_storage/html/RDA_hierarchy) it works with your JavaScript??

**Comment by mcm104** [comment]
Oh good!! The JS is I think verbatim from a [W3 tutorial](https://www.w3schools.com/howto/howto_js_treeview.asp) so if something was broken I wouldn't know how to fix it...

**Comment by cspayne** [comment]
@briesenberg07 link has been added to sinopia_maps wiki here: https://github.com/uwlib-cams/sinopia_maps/wiki/author_04_find_prop_set#overview-of-prop_set-instances

**Comment by briesenberg07** [comment]
Thank you for this (and all of your other) wiki updates @cspayne !  
I "fancied up" [the link](https://github.com/uwlib-cams/sinopia_maps/wiki/author_04_find_prop_set#overview-of-prop_set-instances) to the overview doc a bit, and avoided using "here" as link hot-text. I recently learned that this can cause accessibility problems for people using screen readers to review the link text on a page ("here, here, here" etc.).
