### ISSUE TITLE
[?] fix ridiculous length of form_order decimals, update guidance

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#24]
We don't need more than 5 decimal places at most for this??

**Comment by mcm104** [comment]
Saw this and wrote a Python script that can go in and adjust form order numbers: <https://github.com/uwlib-cams/map_storage/blob/main/py/adjust_form_order.py>

**Comment by briesenberg07** [comment]
Thank you @mcm104 !

You've edited quite a few `implementation_set`s at this point. *Do you have any thoughts about how many decimal places we might want to allow for readjusting `form_order` values as needed?*  

For the monographs Work template, I've been adding `form_order` values in increments of 5. (Top PT in the RT has `0.0000000005`, next has `0.0000000010`, next `0.0000000015`, etc.) Thinking that leaving space in this way can accommodate future property additions or rearrangements without having to edit lots of form_orders.  

But even so, I don't think we need a full 10 decimal places...

**Comment by mcm104** [comment]
I'm not sure we need anything beyond just one (0.1, 0,2, etc.).

At least in my work, I never had to change which property came first in the form order -- 0.0000000001 was pretty safe. I only ever had to change form order values when I had to introduce a new property between two properties that had already been numbered -- and in these cases, all the zeros were useless; I had to add more digits _after_. e.g., if I had property A at 0.0000000002 and property B at 0.0000000003 and want to put property C between them, those first nine 0's don't matter. If I don't want to change everything that comes after (B) 0.0000000003, I would have to do something like (A) 0.00000000021, (C) 0.00000000022, and (B) 0.0000000003. There's really no difference between this and 0.21, 0.22, and 0.3, which is much clearer for a human editor to read.

Then if we hypothetically _did_ need to swap out the first property, that could also be done with adding an extra digit on the end, i.e. 0.1 becomes 0.12 and the new first property becomes 0.11.

And if we wanted to use the Python script, whatever mess we make would get sorted out there. e.g. if we have 0.111111, 0.111112, and 0.111115, the Python script would just update these to 1, 2, and 3. (But the Python script could also easily be edited to start on 0.1 and increase by 0.5 each PT, or whatever values we prefer.)

**Comment by mcm104** [comment]
Coming back to this after editing the work prop set:

Your form order got much larger than mine! I have to imagine that the work RT will have the most properties, so since that made it into triple digits, I'm thinking three digits (0.001) should be enough. (I also disagree with myself for originally saying just one when my own property sets got into double digits...)

For now, I'll update the Python script to start at 0.001 and increase by increments of 0.005.

**Comment by mcm104** [comment]
Script is not editing [this property](https://github.com/uwlib-cams/map_storage/blob/06bb4504c7e6f8b4adfb0a7924de144c85e5c089/prop_set_rdaw_p10k.xml#L1770) for whatever reason... Need to investigate, reverting to old form order numbers for now

**Comment by mcm104** [comment]
Update: it was an issue with two properties in the same RT having the same form order value -- it's been [fixed](https://github.com/uwlib-cams/map_storage/commit/b15456d3fb657a4f3a765759c2f63f515dfceb12) and the Python script updated to [print an error message if it happens again](https://github.com/uwlib-cams/map_storage/blob/5654575e4e0a5a84b1de4e242c44a85e790ddec7/py/adjust_form_order.py#L75-L77).
