### ISSUE TITLE
prop_label element validation woes

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#3]
I'd like to require that `<prop_label>` elements in the source have an `xml:lang` attribute with value `'en'`. I've been unable to achieve this so far in the draft schema. My effort to do so in the draft schema is [here](https://github.com/uwlib-cams/map_storage/blob/28c1daa212cca503e35968ec10f04091293e8063/map_storage.xsd#L60-L62).

Error message:
```
Element 'prop_label' is a simple type, so it cannot have attributes, excepting those whose namespace name is identical to 'http://www.w3.org/2001/XMLSchema-instance' and whose [local name] is one of 'type', 'nil', 'schemaLocation' or 'noNamespaceSchemaLocation'. However, the attribute, 'xml:lang' was found.
```

![Error message for the xml:lang attribute](https://user-images.githubusercontent.com/27664966/110741271-3ca8f180-81e9-11eb-98d0-0236872745cf.png)

**Comment by briesenberg07** [comment]
Marking this as low priority because simply dispensing with `xml:lang` attributes in our source file is certainly an option; we don't have any use cases involving outputting derivatives in multiple languages.

**Comment by gerontakos** [comment]
I believe this is what you want to do?  Change this compoexType from
        <xs:complexType name="prop_label_type">
            <xs:attribute ref="xml:lang"/>
        </xs:complexType>
to
        <xs:complexType name="prop_label_type">
            <xs:attribute ref="xml:lang" use="required"/>
        </xs:complexType>
Is that what you want to do?

**Comment by briesenberg07** [comment]
Thanks @gerontakos for providing the method for requiring an `xml:lang` attribute [just above](https://github.com/uwlib-cams/map_storage/issues/3#issuecomment-797033193). This seems to have done the trick, as far as the `xml:lang` attribute on the `prop_label` element goes.

Current error message for `prop_label` element is:
> Element 'prop_label' must have no character or element information item [children], because the type's content type is empty.

Seems additional changes to [the schema for `prop_label`](https://github.com/uwlib-cams/map_storage/blob/a3bfab69e49038fd16573328c85689b09e2f1fb3/map_storage.xsd#L60-L62) are needed.

Thus far my understanding is that making `prop_label` an `xs:simpleType` would allow a text value (as with [`propSet_id`](https://github.com/uwlib-cams/map_storage/blob/a3bfab69e49038fd16573328c85689b09e2f1fb3/map_storage.xsd#L37-L47)), but would not allow the `xml:lang` attribute requirement, so a different setup is needed.

**Comment by gerontakos** [comment]
You want to allow an element to have a text node with string values (that'll be like any sequence of characters, including numbers and symbols) and also an attribute for xml:lang.

Try this: Inside a complexType, ask for simpleContent that expects a string text node (in the schema) and extend the string so that you can insert the desired attribute.

  <xs:complexType name="label_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

**Comment by briesenberg07** [comment]
These woes have been conquered thanks to @gerontakos !
Some lang tag attribute questions remain but I'll put these in a separate issue.
Details below:
```
    <xs:complexType name="label_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
```
![image](https://user-images.githubusercontent.com/27664966/122838003-fb28e780-d2a9-11eb-8bc2-99334abc3354.png)
