### ISSUE TITLE
wiki fixes for new localIDs

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#31]
Once #28 is closed, fixes will be needed in both the [sinopia_maps wiki](https://github.com/uwlib-cams/sinopia_maps/wiki) and the [map_storage wiki](https://github.com/uwlib-cams/map_storage/wiki) where the construction of localid attributes is discussed.

**Comment by cspayne** [comment]
@briesenberg07 It looks like [manage_01_xslt](https://github.com/uwlib-cams/map_storage/wiki/manage_01_xslt) is already up to date. I don't believe there is any other location in the wikis where the construction of localid attributes is discussed.

**Comment by briesenberg07** [comment]
Thank you for checking @cspayne -- I made the updates!
