### ISSUE TITLE
add instruction for new implementation sets *under* existing implementation sets

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#32]
I think that once localid creation for `implementation_set` is revamped, new implementation sets will always need to be added *underneath* (following, subsequent to) existing ones

**Comment by cspayne** [comment]
[author_05_adding_properties_to_RTs](https://github.com/uwlib-cams/sinopia_maps/wiki/author_05_adding_properties_to_RTs#adding-a-new-implementation_set-to-a-property-that-already-contains-an-implementation_set)
