### ISSUE TITLE
Make 003_01_convert_csv_to_xml.xsl work

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#33]
The [output from this stylesheet](https://github.com/uwlib-cams/map_storage/blob/937d83469e434c780bf0b480c691465ad15ff4ad/xml/RDA_alignments.xml) is used to [add Toolkit URLs to Sinopia resource templates](https://github.com/uwlib-cams/map_storage/blob/937d83469e434c780bf0b480c691465ad15ff4ad/xsl/003_02_add_toolkit_URLs.xsl), and to [generate](https://github.com/uwlib-cams/map_storage/blob/937d83469e434c780bf0b480c691465ad15ff4ad/xsl/005_RDA_hierarchy.xsl) the simple hierarchical view of RDA/RDF properties, but it doesn't currently work.

**Comment by briesenberg07** [comment]
Won't be a problem if the [property-to-Toolkit-alignments](https://www.rdaregistry.info/Aligns/alignRDA2TK.html) never change...

**Comment by cspayne** [comment]
@briesenberg07 003_02_add_toolkit_URLS.xsl used to call 003_01_convert_csv_to_xml.xsl, which is how it was run. 
It looks like you removed that line of code in [this commit](https://github.com/uwlib-cams/map_storage/commit/19404973717df22015770c7df41de50802506d70). 

I went ahead and added the match attrib to xsl:template within 003_01_convert_csv_to_xml.xsl so that it can be run without running 003_002_add_toolkit_URLs.xsl.

**Comment by briesenberg07** [comment]
Thank you @cspayne ! I just ran the stylesheet with the transformation scenario below and it worked.  

Looking at the older version of the 003_02 stylesheet, it [used `xsl:include`](https://github.com/uwlib-cams/map_storage/blob/e0ff9364e111bcbe7350ee325107f1a298a36302/xsl/003_02_add_toolkit_URLs.xsl#L8) to allow for calling templates from the csv-to-xml stylesheet, but I don't think it ever used `xsl:call-template` or any other method to do so.  

The crucial fix to 003_01 seems to me to be your adding [the match attribute (back?) to the `xsl:template` element](https://github.com/uwlib-cams/map_storage/blob/561f92f53d1c56eee4a75cd06608537e333ab3ef/xsl/003_01_convert_csv_to_xml.xsl#L22). I hadn't noticed that it was missing; I believe this is why the stylesheet didn't function. 

Thanks again for fixing!


![image](https://github.com/uwlib-cams/map_storage/assets/27664966/4da53b7a-76ff-420b-80fc-2c1be1b56385)
![image](https://github.com/uwlib-cams/map_storage/assets/27664966/9540ac6c-98bf-4514-9cab-b05f9634ac6a)
