### ISSUE TITLE
clean up py/

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#38]
I believe we have old, unnecessary files in map_storage/[py](https://github.com/uwlib-cams/map_storage/tree/main/py). 

I believe most of these kinds of files will be from before @cspayne 's time. I will look and delete. 

@cspayne please let me know if you are aware of files which definitely need to stay, or can definitely be deleted. Thanks!

**Comment by briesenberg07** [comment]
Thank you @cspayne !

**Comment by briesenberg07** [comment]
**KEEP**
- py/update_prop_sets.py
- py/prop_storage.py
- py/store_props.py
- py/add_props.py

**DELETE**
- py/addlocalid.py
- py/adjust_form_order.py
- py/CommentedTreeBuilder.py
- py/test_build_update.py
- py/test_post_github_issue.py

**PLUS BONUS DELETE**
- prop_set_test.xml
- prop_set_test1.xml

**IGNORE**
- py/__pycache__/\*

\* @cspayne should __pycache__not be ignored? I noticed that [we currently only ignore some files](https://github.com/uwlib-cams/map_storage/blob/86d38dde1e4921028786f7288873a365f719e603/.gitignore#L2-L4), but don't currently ignore the whole thing.

**Comment by cspayne** [comment]
@briesenberg07 I believe that __pycache__ can be ignored as a whole.
