### ISSUE TITLE
Need to constrain @ values to xsd:anyURI

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#4]
The [constraint I've created](https://github.com/uwlib-cams/map_storage/blob/454996536335c062643d766c40ca6e06f40b7755/map_storage.xsd#L64-L70) for the [`prop_iri` element](https://github.com/uwlib-cams/map_storage/blob/454996536335c062643d766c40ca6e06f40b7755/map_storage.xsd#L51) doesn't seem to be actually constraining the format of attribute values--no error messages on validation.

![image](https://user-images.githubusercontent.com/27664966/121632701-49322580-ca36-11eb-9a54-c05a2692c86e.png)

**Comment by gerontakos** [comment]
xs:anyURI is useless. Everything is allowed; there's apparently no way to detect a valid IRI. XSD even allows characters reserved in the IETF spec. 

I believe you want to allow only http IRIs. I would still create the iri_type as a complexType, then define an attrbute named "iri" that is a simpleType that restricts xs:anyURI to a pattern. What you enter as your pattern is up for grbs. I would do this:

 <xs:complexType name="iri_type">
                <xs:attribute name="iri">
                    <xs:simpleType>
                        <xs:restriction base="xs:anyURI">
                            <xs:pattern value="https?://.*"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
    </xs:complexType>

**Comment by briesenberg07** [comment]
Thanks @gerontakos !
Looks good now. I made the IRI validation as restrictive as possible, which will require updating in future if/when we want to bring sources other than the Registry in...
```
<xs:complexType name="iri_type">
       <xs:attribute name="iri">
           <xs:simpleType>
               <xs:restriction base="xs:anyURI">
                   <!-- IRI validation pattern -->
                   <!-- UPDATE PATTERN to allow sources other than RDA Registry -->
                   <xs:pattern value="http:\/\/rdaregistry\.info\/Elements\/\S*"/>
               </xs:restriction>
           </xs:simpleType>
       </xs:attribute>
    </xs:complexType>
```
![image](https://user-images.githubusercontent.com/27664966/122837003-33c7c180-d2a8-11eb-9f51-3b9344177d5d.png)
