### ISSUE TITLE
Move sinopia_maps.xml to map_storage

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/map_storage#41]
@cspayne has suggested this.  

Would have benefits:
- Template authors would only need to clone one repository
- If keeping institution, resource, format, and user elements in sinopia_maps.xml in the uwsinopia namespace, these elements could be configured to include prefixes; this would allow easier copy-pasting into a new implementation set
Would require:
- Update to stylesheets
   - prop_set-to-rdfxml
   - prop_set-to-html
   - other?

**Comment by briesenberg07** [comment]
Note that if this happens, the authoring pages in sinopia_maps wiki should probably go over to map_storage as well.

**Comment by briesenberg07** [comment]
@cspayne please let me know if you need assistance or have questions related to .xsd / namespaces!

**Comment by cspayne** [comment]
[issue templates related to creating RTs](https://github.com/uwlib-cams/map_storage/issues) have been moved to map_storage.

**Comment by cspayne** [comment]
[Authoring sinopia rts wiki](https://github.com/uwlib-cams/map_storage/wiki) moved to map_storage

**Comment by cspayne** [comment]
still need to ensure there are no problems opening map_storage.xpr if sinopia_maps folder does not exist locally.

**Comment by cspayne** [comment]
> still need to ensure there are no problems opening map_storage.xpr if sinopia_maps folder does not exist locally.

map_storage.xpr opens just fine but shows that the sinopia_maps folder is missing. Should we keep as is and just note that it is not necessary to have a local copy of sinopia_maps, or should we remove the repo from the oxygen xml project?

**Comment by briesenberg07** [comment]
Let's remove the sinopia_maps folder from map_storage.xpr
