### ISSUE TITLE
Generating remark urls for implementation sets with >1 rt ids 

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/map_storage#46]
@briesenberg07 
While testing the stylesheet for generating remark urls I came across this issue - 
When an implementation set contains more than one rt_id (and thus has more than one of some id elements), it would then need more than one remark url to link to the correct html page. 

The simplest solution I can see to this is to only allow one rt id per implementation set (and simply copying if you want to create the same set for a different rt) - but is this the best solution?

**Comment by briesenberg07** [comment]
Hello Cypress!
I wonder if the following would solve the problem:

- Do not store remarkUrl values in prop_sets (I would remove the [remark_url](https://github.com/uwlib-cams/sinopia_maps/blob/a09933920d34e08f1b89dfa58c6a38373915ac0b/xsd/uwsinopia.xsd#L488) element from uwsinopia.xsd)
- Generate remark URL values\*\* on-demand as-needed for output to RDF RTs, which is the only place the full remark URLs will be recorded (@localid_implementation_set values will be used as anchor IDs in HTML). 

***\*\*remark URL components***
```
[HTML RT base URL] + # + [@localid_implementation_set value]
```

What do you think?

**Comment by briesenberg07** [comment]
So, you'd end up changing [the code in 001_04_define_all_pts.xsl](https://github.com/uwlib-cams/sinopia_maps/blob/a09933920d34e08f1b89dfa58c6a38373915ac0b/xsl/001_04_define_all_pts.xsl#L113-L127).

**Comment by cspayne** [comment]
@briesenberg07 sounds like a plan!

**Comment by briesenberg07** [comment]
To-dos:

- [ ] Remove remark_url element from uwsinopia.xsd ( @briesenberg07 )
- [ ] Remove existing remark_url elements/values from prop_sets ( @briesenberg07 )
- [ ] Update remark URL output in 001_04_define_all_pts.xsl ( @cspayne )
- [ ] Remove prop_set > remark_url element guidance from wiki ( @briesenberg07 )

**Comment by cspayne** [comment]
001_04_define_all_pts.xsl and the rdfxml files in sinopia_maps have been updated
