### ISSUE TITLE
toolkit url for uwRdaExtension property templates 

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/map_storage#49]
@briesenberg07 
uwsinopia.xsd requires the element uwsinopia:toolkit to appear within a sinopia element. 
This causes validation errors when creating property templates in prop_set_uwRdaExtension.xml, as these properties do not have a toolkit link.

**Comment by briesenberg07** [comment]
🤯 🤯 🤯 
Of course. 
I don't have a solution for this right now. Want to avoid the need for a separate schema for the RDA Extension prop_set. 
If it's just one validation error for the prop_set, and if validation still functions as expected for the implementation_set and guidance_set for the prop, OK to put this off?

**Comment by cspayne** [comment]
Sounds good! I'll make sure that it validates okay and then I may have to make some minor adjustments to the xml to hml script to account for prop sets that do not have links.

**Comment by cspayne** [comment]
@briesenberg07 
Validation is working fine!
One question for uwRdaExtension properties: will there ever be subproperties?

**Comment by briesenberg07** [comment]
> One question for uwRdaExtension properties: will there ever be subproperties?

Unknown, but I don't think there are any plans develop the [University of Washington Libraries RDA Application Profile Extension](https://doi.org/10.6069/uwlib.55.d.4) into a complex vocabulary. Tagging @CECSpecialistI and @gerontakos in case they have any thoughts on this.

@cspayne are you asking with regard to whether we might ever need to support adding all subproperties of a given RDAExt prop to a property template, in the way we do with RDA properties?

**Comment by cspayne** [comment]
> > One question for uwRdaExtension properties: will there ever be subproperties?
> 
> Unknown, but I don't think there are any plans develop the [University of Washington Libraries RDA Application Profile Extension](https://doi.org/10.6069/uwlib.55.d.4) into a complex vocabulary. Tagging @CECSpecialistI and @gerontakos in case they have any thoughts on this.
> 
> @cspayne are you asking with regard to whether we might ever need to support adding all subproperties of a given RDAExt prop to a property template, in the way we do with RDA properties?

Yes! I am updating the xml to html scripts and wanted to know, as this involves using the property xml file (in this case I believe it would be https://www.lib.washington.edu/static/public/cams/data/localResources/rdaApplicationProfileExtension-1-0-1.rdf) to retrieve the property label based on the iri. 
However, I believe if a uwRdaExtension property template has specific properties selected as subprops in the prop_set file, the labels can be retrieved from there.
